# -*- coding: utf-8 -*-
"""Basic_Task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PolWcMKx8aEBqdrpkQdNdKSLWpTyd8Dn
"""

# ==============================================================================
# CELL 1. IMPORT LIBRARIES
#
# This cell imports all the Python libraries required for data manipulation,
# visualization, machine learning, and model evaluation.
#
# These libraries will be used throughout the entire notebook.
# ==============================================================================

# Import pandas for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical computations
import numpy as np

# Import matplotlib for creating graphs and visualizations
import matplotlib.pyplot as plt

# Import seaborn for more attractive statistical visualizations
import seaborn as sns

# Import pathlib for easier file and folder management
from pathlib import Path

# Import Linear Regression model from scikit-learn
from sklearn.linear_model import LinearRegression

# Import function to split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# Import evaluation metrics for regression models
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Ignore unnecessary warning messages
import warnings
warnings.filterwarnings("ignore")

# Set a clean plotting style
plt.style.use("ggplot")

# Set default figure size for all plots
plt.rcParams["figure.figsize"] = (10,6)

# Display confirmation message
print("Libraries imported successfully.")

# ==============================================================================
# CELL 2. MOUNT GOOGLE DRIVE
#
# This cell mounts Google Drive so that the notebook can directly access
# the dataset and automatically save all outputs.
# ==============================================================================

# Import Google Drive utility
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Display confirmation message
print("Google Drive mounted successfully.")

# ==============================================================================
# CELL 3. DEFINE FILE PATHS
#
# This cell defines where the dataset is located and creates folders
# where all charts, tables, and prediction results will be saved.
# ==============================================================================

# Define the location of your Google Drive folder
DATA_DIR = Path("/content/drive/MyDrive/LinearRegressionLab")

# Specify the dataset filename
FILE_PATH = DATA_DIR / "4) house Prediction Data Set.csv"

# Create an output folder
OUTPUT_DIR = DATA_DIR / "LinearRegression_Output"

# Create subfolders for better organization
CHARTS_DIR = OUTPUT_DIR / "Charts"
TABLES_DIR = OUTPUT_DIR / "Tables"

# Create the folders if they do not already exist
CHARTS_DIR.mkdir(parents=True, exist_ok=True)
TABLES_DIR.mkdir(parents=True, exist_ok=True)

# Display confirmation
print("Directories are ready.")

# ==============================================================================
# CELL 4. LOAD THE RAW DATASET
#
# The provided dataset contains all values merged into a single column.
# This cell loads the raw file exactly as provided before cleaning.
# ==============================================================================

# Read the raw dataset
raw_df = pd.read_csv(FILE_PATH)

# Display the first five rows
print("First five rows of the raw dataset:")
display(raw_df.head())

# Display the shape of the raw dataset
print(f"\nRaw Dataset Shape: {raw_df.shape}")

# ==============================================================================
# CELL 5. DATA CLEANING
#
# The dataset stores all observations inside a single column separated
# by spaces. This cell separates each value into its own column,
# assigns meaningful feature names, and converts all values to numeric.
# ==============================================================================

# Extract the single column containing all values
single_column = raw_df.iloc[:,0]

# Split every row using whitespace as the separator
split_data = single_column.str.split(expand=True)

# Assign official Boston Housing column names
split_data.columns = [
    "CRIM",
    "ZN",
    "INDUS",
    "CHAS",
    "NOX",
    "RM",
    "AGE",
    "DIS",
    "RAD",
    "TAX",
    "PTRATIO",
    "B",
    "LSTAT",
    "MEDV"
]

# Convert every column into numeric values
df = split_data.apply(pd.to_numeric)

# Display the cleaned dataset
print("Cleaned Dataset")
display(df.head())

# Display dataset dimensions
print(f"\nRows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

# Save the cleaned dataset
df.to_csv(TABLES_DIR / "Cleaned_Dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

# ==============================================================================
# CELL 6. DATASET INFORMATION
#
# This cell examines the structure, data types, descriptive statistics,
# and missing values of the cleaned dataset.
# ==============================================================================

print("="*60)
print("DATASET INFORMATION")
print("="*60)

# Display information about the dataset
df.info()

print("\n")

# Display descriptive statistics
display(df.describe())

print("\nMissing Values\n")

# Count missing values
display(df.isnull().sum())

# ==============================================================================
# CELL 7. CHECK FOR DUPLICATE RECORDS
#
# Duplicate records can affect the performance of a machine learning model.
# This cell identifies duplicate observations and removes them if any exist.
# ==============================================================================

# Count duplicate rows
duplicates = df.duplicated().sum()

print(f"Duplicate Rows Found: {duplicates}")

# Remove duplicates if present
df = df.drop_duplicates()

print(f"Dataset Shape after Removing Duplicates: {df.shape}")

# ==============================================================================
# CELL 8. CORRELATION ANALYSIS
#
# This cell computes the Pearson correlation coefficients between all variables.
# Correlation values range from -1 to 1:
#
#   +1 : Perfect positive relationship
#    0 : No relationship
#   -1 : Perfect negative relationship
#
# The correlation matrix helps identify which feature has the strongest
# relationship with the target variable (MEDV).
# ==============================================================================

# Calculate the correlation matrix
correlation_matrix = df.corr()

# Display the correlation matrix
display(correlation_matrix)

# Save the correlation matrix
correlation_matrix.to_csv(TABLES_DIR / "Correlation_Matrix.csv")

print("Correlation matrix saved successfully.")

# ==============================================================================
# CELL 9. CORRELATION HEATMAP
#
# This heatmap visualizes the relationships among all numerical variables.
# Darker colors indicate stronger positive or negative correlations.
# ==============================================================================

# Create the heatmap
plt.figure(figsize=(12,10))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    linewidths=0.5
)

# Add title
plt.title("Correlation Heatmap of Boston Housing Dataset")

# Save the figure
plt.savefig(CHARTS_DIR / "Correlation_Heatmap.png",
            dpi=300,
            bbox_inches="tight")

# Display the heatmap
plt.show()

# ==============================================================================
# CELL 10. FEATURE SELECTION
#
# Since this task requires a Simple Linear Regression model, only ONE predictor
# variable will be used.
#
# This cell automatically selects the feature with the strongest absolute
# correlation with the target variable (MEDV).
# ==============================================================================

# Calculate the correlation of every feature with MEDV
target_correlation = correlation_matrix["MEDV"].drop("MEDV")

# Sort correlations by absolute value
sorted_corr = target_correlation.abs().sort_values(ascending=False)

# Display correlations
display(sorted_corr)

# Select the best predictor
best_feature = sorted_corr.index[0]

print(f"The selected predictor variable is: {best_feature}")

# Store predictor and target names
FEATURE = best_feature
TARGET = "MEDV"

# ==============================================================================
# CELL 11. SCATTER PLOT
#
# This scatter plot visualizes the relationship between the selected predictor
# variable and the target variable.
#
# A linear pattern suggests that Simple Linear Regression is appropriate.
# ==============================================================================

# Create scatter plot
plt.figure(figsize=(8,6))

plt.scatter(
    df[FEATURE],
    df[TARGET],
    alpha=0.7
)

# Label the axes
plt.xlabel(FEATURE)
plt.ylabel(TARGET)

# Add title
plt.title(f"{FEATURE} vs {TARGET}")

# Save figure
plt.savefig(
    CHARTS_DIR / "Scatter_Plot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==============================================================================
# CELL 12. PREPARE FEATURES AND TARGET
#
# Machine learning models require:
#
# X = Predictor variable(s)
# y = Target variable
#
# Since this is Simple Linear Regression, X contains only one feature.
# ==============================================================================

# Store predictor variable
X = df[[FEATURE]]

# Store target variable
y = df[TARGET]

print("Predictor Variable:")
display(X.head())

print("\nTarget Variable:")
display(y.head())

# ==============================================================================
# CELL 13. SPLIT THE DATASET
#
# The dataset is divided into:
#
# 80% Training Data
# 20% Testing Data
#
# The model learns from the training data and is evaluated using unseen
# testing data.
# ==============================================================================

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print(f"Training Samples : {len(X_train)}")
print(f"Testing Samples  : {len(X_test)}")

# ==============================================================================
# CELL 14. BUILD THE LINEAR REGRESSION MODEL
#
# This cell creates and trains a Simple Linear Regression model using
# the training dataset.
# ==============================================================================

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

print("Linear Regression Model Successfully Trained.")

# ==============================================================================
# CELL 15. MODEL COEFFICIENTS
#
# The intercept is the predicted value when the predictor is zero.
#
# The coefficient indicates how much the predicted house price changes
# for every one-unit increase in the selected feature.
# ==============================================================================

# Extract intercept
intercept = model.intercept_

# Extract coefficient
coefficient = model.coef_[0]

print(f"Intercept : {intercept:.4f}")
print(f"Coefficient ({FEATURE}) : {coefficient:.4f}")

# Save coefficients
coef_df = pd.DataFrame({
    "Feature":[FEATURE],
    "Coefficient":[coefficient],
    "Intercept":[intercept]
})

coef_df.to_csv(
    TABLES_DIR / "Model_Coefficients.csv",
    index=False
)

# ==============================================================================
# CELL 16. MAKE PREDICTIONS
#
# The trained model predicts house prices using the testing dataset.
# ==============================================================================

# Predict house prices
y_pred = model.predict(X_test)

# Create comparison table
prediction_df = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

display(prediction_df.head())

# Save predictions
prediction_df.to_csv(
    TABLES_DIR / "Predictions.csv",
    index=False
)

print("Predictions saved successfully.")

# ==============================================================================
# CELL 17. MODEL EVALUATION
#
# This cell evaluates the performance of the Simple Linear Regression model.
#
# Metrics Used:
#
# R² Score
# Mean Absolute Error (MAE)
# Mean Squared Error (MSE)
# Root Mean Squared Error (RMSE)
# ==============================================================================

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

# Display results
print("="*50)
print("MODEL PERFORMANCE")
print("="*50)

print(f"R² Score              : {r2:.4f}")
print(f"Mean Absolute Error   : {mae:.4f}")
print(f"Mean Squared Error    : {mse:.4f}")
print(f"Root Mean Squared Error : {rmse:.4f}")

# Save metrics
metrics_df = pd.DataFrame({
    "Metric":["R² Score","MAE","MSE","RMSE"],
    "Value":[r2,mae,mse,rmse]
})

metrics_df.to_csv(
    TABLES_DIR / "Evaluation_Metrics.csv",
    index=False
)

# ==============================================================================
# CELL 18. REGRESSION LINE VISUALIZATION
#
# This cell visualizes the fitted Simple Linear Regression model.
#
# The blue dots represent the actual observations, while the red line
# represents the best-fit regression line learned by the model.
#
# A regression line that closely follows the data points indicates a
# stronger linear relationship between the predictor and the target.
# ==============================================================================

# Create a new figure
plt.figure(figsize=(8,6))

# Plot the actual data points
plt.scatter(
    X,
    y,
    alpha=0.7,
    color="steelblue",
    label="Actual Data"
)

# Generate predictions using the entire dataset
y_line = model.predict(X)

# Plot the regression line
plt.plot(
    X,
    y_line,
    color="red",
    linewidth=3,
    label="Regression Line"
)

# Label the axes
plt.xlabel(FEATURE)
plt.ylabel(TARGET)

# Add title
plt.title(f"Simple Linear Regression: {FEATURE} vs {TARGET}")

# Display legend
plt.legend()

# Save the figure
plt.savefig(
    CHARTS_DIR / "Regression_Line.png",
    dpi=300,
    bbox_inches="tight"
)

# Display the plot
plt.show()

# ==============================================================================
# CELL 19. ACTUAL VS PREDICTED VALUES
#
# This plot compares the actual house prices with the predicted house prices.
#
# If the model performs well, most points should lie close to the diagonal line.
# ==============================================================================

# Create figure
plt.figure(figsize=(8,6))

# Scatter plot of actual vs predicted values
plt.scatter(
    y_test,
    y_pred,
    alpha=0.7
)

# Draw the ideal prediction line
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color="red",
    linewidth=2,
    linestyle="--"
)

# Label axes
plt.xlabel("Actual House Price")
plt.ylabel("Predicted House Price")

# Add title
plt.title("Actual vs Predicted Values")

# Save figure
plt.savefig(
    CHARTS_DIR / "Actual_vs_Predicted.png",
    dpi=300,
    bbox_inches="tight"
)

# Display plot
plt.show()

# ==============================================================================
# CELL 20. RESIDUAL PLOT
#
# Residuals are the differences between the actual and predicted values.
#
# A good regression model should produce residuals that are randomly
# scattered around zero without any obvious pattern.
# ==============================================================================

# Calculate residuals
residuals = y_test - y_pred

# Create figure
plt.figure(figsize=(8,6))

# Scatter plot of predicted values versus residuals
plt.scatter(
    y_pred,
    residuals,
    alpha=0.7
)

# Draw horizontal reference line
plt.axhline(
    y=0,
    color="red",
    linestyle="--",
    linewidth=2
)

# Label axes
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")

# Add title
plt.title("Residual Plot")

# Save figure
plt.savefig(
    CHARTS_DIR / "Residual_Plot.png",
    dpi=300,
    bbox_inches="tight"
)

# Display plot
plt.show()

# ==============================================================================
# CELL 21. DISTRIBUTION OF RESIDUALS
#
# This histogram shows how the residuals are distributed.
#
# Ideally, the residuals should resemble a normal distribution centered
# around zero, indicating that the model's prediction errors are random.
# ==============================================================================

# Create figure
plt.figure(figsize=(8,6))

# Plot histogram of residuals
sns.histplot(
    residuals,
    bins=20,
    kde=True
)

# Label axes
plt.xlabel("Residual")
plt.ylabel("Frequency")

# Add title
plt.title("Distribution of Residuals")

# Save figure
plt.savefig(
    CHARTS_DIR / "Residual_Distribution.png",
    dpi=300,
    bbox_inches="tight"
)

# Display plot
plt.show()

# ==============================================================================
# CELL 22. MODEL SUMMARY
#
# This cell provides a summary of the trained Simple Linear Regression model.
#
# It reports the selected predictor, regression equation, and performance
# metrics to help interpret the model's predictive ability.
# ==============================================================================

print("=" * 70)
print("SIMPLE LINEAR REGRESSION MODEL SUMMARY")
print("=" * 70)

print(f"\nTarget Variable     : {TARGET}")
print(f"Predictor Variable  : {FEATURE}")

print("\nRegression Equation:")
print(f"{TARGET} = {intercept:.4f} + ({coefficient:.4f} × {FEATURE})")

print("\nModel Performance Metrics")
print("-" * 40)

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"MSE      : {mse:.4f}")
print(f"RMSE     : {rmse:.4f}")

print("\nInterpretation:")
print("-" * 40)

print(
    f"For every one-unit increase in {FEATURE}, "
    f"the predicted value of {TARGET} changes by "
    f"{coefficient:.4f} units."
)

print(
    "\nThe R² Score indicates the proportion of the variance "
    "in the target variable explained by the predictor variable."
)

print(
    "Lower MAE, MSE, and RMSE values indicate better prediction accuracy."
)

# ==============================================================================
# CELL 23. SAVE COMPLETE ANALYSIS REPORT
#
# This cell compiles the key outputs of the analysis into a single summary
# table and saves it to Google Drive.
# ==============================================================================

# Create summary table
summary_df = pd.DataFrame({
    "Item": [
        "Dataset Rows",
        "Dataset Columns",
        "Predictor Variable",
        "Target Variable",
        "Intercept",
        "Coefficient",
        "R² Score",
        "Mean Absolute Error",
        "Mean Squared Error",
        "Root Mean Squared Error"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        FEATURE,
        TARGET,
        intercept,
        coefficient,
        r2,
        mae,
        mse,
        rmse
    ]
})

# Display summary
display(summary_df)

# Save summary table
summary_df.to_csv(
    TABLES_DIR / "Analysis_Summary.csv",
    index=False
)

print("\nAnalysis summary saved successfully.")
print(f"\nAll outputs have been saved to:\n{OUTPUT_DIR}")